spring:
  jpa:
    open-in-view: false
  datasource:
    url: jdbc:h2:mem:tesdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;
    username: sa
    password:
    testWhileIdle: true
    validationQuery: SELECT 1
  jackson:
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false

logging:
  level:
    root: INFO
    org.springframework: WARN
    org.hibernate: ERROR
    com.fasterxml.jackson: DEBUG

move:
  strategy: offensive #(always attack) | defensive(stay and attack) | swift(dodge always when revive)